[project]
name = "projekt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ilthermopy>=1.1.0",
    "kaleido==0.2.1",
    "padelpy>=0.1.16",
    "pandas>=2",
    "pycaret==3.3.2",
]
